# Generated by Django 4.2.11 on 2024-09-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thedataeditor", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="nodecategory",
            old_name="html_id",
            new_name="icon",
        ),
    ]
