# Generated by Django 4.2.11 on 2024-09-16 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedataeditor", "0003_alter_workflow_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflow",
            name="name",
            field=models.CharField(max_length=18),
        ),
    ]
