# Generated by Django 4.2.11 on 2024-09-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thedataeditor", "0004_alter_workflow_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflow",
            options={"ordering": ["-created", "-updated"]},
        ),
    ]
