# Generated by Django 4.2.11 on 2025-06-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thedataeditor', '0005_alter_workflow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='node',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
