# Generated by Django 4.2.11 on 2025-06-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thedataeditor', '0006_node_disabled_node_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
    ]
