# Generated by Django 4.2.11 on 2024-05-06 16:21

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_flat_button_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_flat_button_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_outline_button_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_outline_button_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_subtitle",
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="landing_page_box_subtitle",
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="landing_page_box_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="landing_page_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="landing_page_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services",
            field=wagtail.fields.StreamField(
                [
                    (
                        "service",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "icon",
                                    wagtail.blocks.CharBlock(
                                        help_text="https://boxicons.com/ example bx bxs-user"
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock()),
                                ("subtitle", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="services_title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
