# Generated by Django 4.2.11 on 2024-08-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_contactform"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactForm",
        ),
    ]
