# Generated by Django 4.2.11 on 2024-05-06 16:41

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_homepage_hero_flat_button_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="hero_flat_button_url",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_outline_button_url",
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="services",
            field=wagtail.fields.StreamField(
                [
                    (
                        "service",
                        wagtail.blocks.StructBlock(
                            [
                                ("icon", wagtail.blocks.CharBlock()),
                                ("title", wagtail.blocks.CharBlock()),
                                ("subtitle", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    )
                ],
                null=True,
            ),
        ),
    ]
