# Generated by Django 4.2.11 on 2025-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_websites'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
