# Generated by Django 4.2.11 on 2025-06-03 11:27

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0005_homepage_services_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='landing_page_box_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='landing_page_box_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='landing_page_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='landing_page_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='websites',
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_bottom_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_bottom_image_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_description',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_top_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editor_top_image_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.RichTextBlock())]))], null=True),
        ),
    ]
