# Generated by Django 4.2.11 on 2025-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_landing_page_box_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='try_editor_description',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_subtitle_box',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_subtitle_signup',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='try_editor_username',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
