# Generated by Django 4.2.11 on 2025-06-03 13:18

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_try_editor_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='portfolio_items',
            field=wagtail.fields.StreamField([('portfolio_item', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=100, required=True)), ('client', wagtail.blocks.CharBlock(max_length=100, required=True)), ('client_logo', wagtail.images.blocks.ImageChooserBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('platform', wagtail.blocks.CharBlock(max_length=100, required=True)), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'], required=True)), ('technologies', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(required=True))]), required=True)), ('website_url', wagtail.blocks.URLBlock(required=False)), ('play_store_url', wagtail.blocks.URLBlock(label='Google Play Store URL', required=False)), ('app_store_url', wagtail.blocks.URLBlock(label='Apple App Store URL', required=False)), ('year', wagtail.blocks.IntegerBlock(max_value=2100, min_value=2000, required=True))]))], null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
