# Generated by Django 4.2.11 on 2025-06-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_portfolio_items_homepage_portfolio_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='try_editor_password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='try_editor_username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
