# Generated by Django 4.2.11 on 2025-06-03 17:51

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_homepage_try_editor_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_box_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_subtitle',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_media_items',
            field=wagtail.fields.StreamField([('social_media', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('link', wagtail.blocks.URLBlock())]))], null=True),
        ),
    ]
