# Generated by Django 4.2.11 on 2024-05-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BettingTips",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("games", models.JSONField()),
                ("host_sc_mse", models.FloatField()),
                ("host_sc_r_squared", models.FloatField()),
                ("guest_sc_mse", models.FloatField()),
                ("guest_sc_r_squared", models.FloatField()),
                ("result_mse", models.FloatField()),
                ("result_r_squared", models.FloatField()),
            ],
        ),
    ]
