# Generated by Django 4.2.11 on 2024-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedatabet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bettingtips",
            name="date",
            field=models.DateField(),
        ),
    ]
