# Generated by Django 4.2.11 on 2024-05-21 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thedatabet", "0002_alter_bettingtips_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bettingtips",
            old_name="guest_sc_r_squared",
            new_name="guest_sc_r2",
        ),
        migrations.RenameField(
            model_name="bettingtips",
            old_name="host_sc_r_squared",
            new_name="host_sc_r2",
        ),
        migrations.RenameField(
            model_name="bettingtips",
            old_name="result_r_squared",
            new_name="result_r2",
        ),
    ]
