# Generated by Django 4.2.11 on 2024-06-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedatabet", "0005_rename_guest_result_mse_bettingtips_result_mse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BetwayOdds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("odds", models.JSONField()),
            ],
        ),
    ]
