# Generated by Django 4.2.11 on 2024-06-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thedatabet", "0006_betwayodds"),
    ]

    operations = [
        migrations.CreateModel(
            name="BettingStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("average", models.JSONField()),
                ("describe", models.JSONField()),
                ("variance", models.JSONField()),
                ("standard_deviation", models.JSONField()),
                ("home_win_len", models.IntegerField()),
                ("home_win_percentage", models.FloatField()),
                ("away_win_len", models.IntegerField()),
                ("away_win_percentage", models.FloatField()),
                ("over_25_len", models.IntegerField()),
                ("over_25_percentage", models.FloatField()),
                ("under_25_len", models.IntegerField()),
                ("under_25_percentage", models.FloatField()),
                ("btts_len", models.IntegerField()),
                ("btts_percentage", models.FloatField()),
                ("home_over_15_len", models.IntegerField()),
                ("home_over_15_percentage", models.FloatField()),
                ("away_over_15_len", models.IntegerField()),
                ("away_over_15_percentage", models.FloatField()),
                ("home_draw_len", models.IntegerField()),
                ("home_draw_percentage", models.FloatField()),
                ("away_draw_len", models.IntegerField()),
                ("away_draw_percentage", models.FloatField()),
            ],
        ),
    ]
