# Generated by Django 4.2.11 on 2025-04-04 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("thedatabet", "0009_delete_bettingstats_delete_betwayodds_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bettingtips",
            name="tips",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wagtaildocs.document",
            ),
        ),
    ]
