# Generated by Django 4.2.11 on 2025-04-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0012_uploadeddocument'),
        ('thedatabet', '0010_alter_bettingtips_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettingtips',
            name='tips',
        ),
        migrations.AddField(
            model_name='bettingtips',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtaildocs.document'),
        ),
        migrations.AddField(
            model_name='bettingtips',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
