# Generated by Django 4.2.11 on 2025-04-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thedatabet', '0011_remove_bettingtips_tips_bettingtips_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TheDataBet',
        ),
    ]
